#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    May 07, 2020 06:23:14 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import BCD_support
import pandas as pd
from sklearn import neighbors
from sklearn.model_selection import train_test_split
import numpy as np
import csv

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = BCD (root)
    BCD_support.init(root, top)
    root.mainloop()

w = None
def create_BCD(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_BCD(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = BCD (w)
    BCD_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_BCD():
    global w
    w.destroy()
    w = None

class BCD:

    def BCD_test(self):
        t = self.thickness_entry.get()
        s = self.Size_Entry.get()
        sa = self.Shape_Entry2_8.get()
        a = self.Adhesion_Entry2_9.get()
        e = self.Epithelial_Entry2_10.get()
        b = self.Bare_Entry2_11.get()
        bl = self.Bland_Entry2_12.get()
        n = self.Normal_Entry2_13.get()
        m = self.Mitoses_Entry2_14.get()

        df = pd.read_csv("breast-cancer-wisconsin.data")
        # print(df.head())
        df.replace("?", -99999, inplace=True)
        df.drop(["id"], axis=1, inplace=True)

        x = np.array(df.drop(["Class"], axis=1))
        y = np.array(df["Class"])

        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

        classifier = neighbors.KNeighborsClassifier(n_neighbors = 23)
        classifier.fit(x_train, y_train)

        accuracy = classifier.score(x_test, y_test)
        print(accuracy * 100)

        dict = {"Thickness": t, "Size": s, "Shape": sa, "Adhesion": a, "Epithelial Size": e, "Bare Nuclei": b,
                "Bland Chromatin": bl, "Normal Nucleoli": n, "Mitoses":m}
        df = pd.DataFrame(dict)
        df.to_csv("BCD_data.csv")
        
        data = pd.read_csv("BCD_data.csv", header = None)
        now_predict = data.values
        # print(type(now_predict))

        # now_predict = np.array()
        now_predict = now_predict.reshape(len(now_predict), -1)
        prediction = classifier.predict(now_predict)
        print(prediction)


    def __init__(self, top=None):
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Sitka Display} -size 14 -weight bold"
        font9 = "-family {Algerian} -size 23 -weight bold"

        top.geometry("1000x800+516+135")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.thickness = tk.Label(top)
        self.thickness.place(relx=0.01, rely=0.125, height=52, width=162)
        self.thickness.configure(background="#ff8080")
        self.thickness.configure(disabledforeground="#a3a3a3")
        self.thickness.configure(foreground="#000000")
        self.thickness.configure(text='''Thickness''')

        self.size = tk.Label(top)
        self.size.place(relx=0.01, rely=0.213, height=48, width=162)
        self.size.configure(background="#ffff80")
        self.size.configure(disabledforeground="#a3a3a3")
        self.size.configure(foreground="#000000")
        self.size.configure(text='''Size''')

        self.shape = tk.Label(top)
        self.shape.place(relx=0.01, rely=0.288, height=48, width=162)
        self.shape.configure(activebackground="#f9f9f9")
        self.shape.configure(activeforeground="black")
        self.shape.configure(background="#80ff80")
        self.shape.configure(disabledforeground="#a3a3a3")
        self.shape.configure(foreground="#000000")
        self.shape.configure(highlightbackground="#d9d9d9")
        self.shape.configure(highlightcolor="black")
        self.shape.configure(text='''Shape''')

        self.adhesion = tk.Label(top)
        self.adhesion.place(relx=0.01, rely=0.363, height=52, width=162)
        self.adhesion.configure(activebackground="#f9f9f9")
        self.adhesion.configure(activeforeground="black")
        self.adhesion.configure(background="#80ffff")
        self.adhesion.configure(disabledforeground="#a3a3a3")
        self.adhesion.configure(foreground="#000000")
        self.adhesion.configure(highlightbackground="#d9d9d9")
        self.adhesion.configure(highlightcolor="black")
        self.adhesion.configure(text='''Adhesion''')

        self.epithelial = tk.Label(top)
        self.epithelial.place(relx=0.01, rely=0.45, height=48, width=162)
        self.epithelial.configure(activebackground="#f9f9f9")
        self.epithelial.configure(activeforeground="black")
        self.epithelial.configure(background="#ff0000")
        self.epithelial.configure(disabledforeground="#a3a3a3")
        self.epithelial.configure(foreground="#000000")
        self.epithelial.configure(highlightbackground="#d9d9d9")
        self.epithelial.configure(highlightcolor="black")
        self.epithelial.configure(text='''Epithelial Size''')

        self.Label2_4 = tk.Label(top)
        self.Label2_4.place(relx=-0.09, rely=0.125, height=28, width=42)
        self.Label2_4.configure(activebackground="#f9f9f9")
        self.Label2_4.configure(activeforeground="black")
        self.Label2_4.configure(background="#d9d9d9")
        self.Label2_4.configure(disabledforeground="#a3a3a3")
        self.Label2_4.configure(foreground="#000000")
        self.Label2_4.configure(highlightbackground="#d9d9d9")
        self.Label2_4.configure(highlightcolor="black")
        self.Label2_4.configure(text='''Label''')

        self.Bare_Nuclei = tk.Label(top)
        self.Bare_Nuclei.place(relx=0.01, rely=0.525, height=48, width=162)
        self.Bare_Nuclei.configure(activebackground="#f9f9f9")
        self.Bare_Nuclei.configure(activeforeground="black")
        self.Bare_Nuclei.configure(background="#008080")
        self.Bare_Nuclei.configure(disabledforeground="#a3a3a3")
        self.Bare_Nuclei.configure(foreground="#000000")
        self.Bare_Nuclei.configure(highlightbackground="#d9d9d9")
        self.Bare_Nuclei.configure(highlightcolor="black")
        self.Bare_Nuclei.configure(text='''Bare Nuclei''')

        self.Normal_Nucleoli = tk.Label(top)
        self.Normal_Nucleoli.place(relx=0.01, rely=0.688, height=48, width=162)
        self.Normal_Nucleoli.configure(activebackground="#f9f9f9")
        self.Normal_Nucleoli.configure(activeforeground="black")
        self.Normal_Nucleoli.configure(background="#8080ff")
        self.Normal_Nucleoli.configure(disabledforeground="#a3a3a3")
        self.Normal_Nucleoli.configure(foreground="#000000")
        self.Normal_Nucleoli.configure(highlightbackground="#d9d9d9")
        self.Normal_Nucleoli.configure(highlightcolor="black")
        self.Normal_Nucleoli.configure(text='''Normal Nucleoli''')

        self.Bland_Chromatin = tk.Label(top)
        self.Bland_Chromatin.place(relx=0.01, rely=0.613, height=47, width=162)
        self.Bland_Chromatin.configure(activebackground="#f9f9f9")
        self.Bland_Chromatin.configure(activeforeground="black")
        self.Bland_Chromatin.configure(background="#804040")
        self.Bland_Chromatin.configure(disabledforeground="#a3a3a3")
        self.Bland_Chromatin.configure(foreground="#000000")
        self.Bland_Chromatin.configure(highlightbackground="#d9d9d9")
        self.Bland_Chromatin.configure(highlightcolor="black")
        self.Bland_Chromatin.configure(text='''Bland Chromatin''')

        self.heading = tk.Label(top)
        self.heading.place(relx=0.0, rely=0.0, height=77, width=1002)
        self.heading.configure(background="#e1031e")
        self.heading.configure(disabledforeground="#a3a3a3")
        self.heading.configure(font=font9)
        self.heading.configure(foreground="#000000")
        self.heading.configure(text='''BREAST CANCER DETECTION''')

        self.mitoses = tk.Label(top)
        self.mitoses.place(relx=0.01, rely=0.763, height=48, width=162)
        self.mitoses.configure(background="#ff80ff")
        self.mitoses.configure(disabledforeground="#a3a3a3")
        self.mitoses.configure(foreground="#000000")
        self.mitoses.configure(text='''Mitoses''')

        self.thickness_entry = tk.Entry(top)
        self.thickness_entry.place(relx=0.18, rely=0.125, height=44
                , relwidth=0.514)
        self.thickness_entry.configure(background="white")
        self.thickness_entry.configure(disabledforeground="#a3a3a3")
        self.thickness_entry.configure(font="TkFixedFont")
        self.thickness_entry.configure(foreground="#000000")
        self.thickness_entry.configure(insertbackground="black")

        self.Size_Entry = tk.Entry(top)
        self.Size_Entry.place(relx=0.18, rely=0.213,height=44, relwidth=0.514)
        self.Size_Entry.configure(background="white")
        self.Size_Entry.configure(disabledforeground="#a3a3a3")
        self.Size_Entry.configure(font="TkFixedFont")
        self.Size_Entry.configure(foreground="#000000")
        self.Size_Entry.configure(insertbackground="black")

        self.Shape_Entry2_8 = tk.Entry(top)
        self.Shape_Entry2_8.place(relx=0.18, rely=0.288, height=44
                , relwidth=0.514)
        self.Shape_Entry2_8.configure(background="white")
        self.Shape_Entry2_8.configure(disabledforeground="#a3a3a3")
        self.Shape_Entry2_8.configure(font="TkFixedFont")
        self.Shape_Entry2_8.configure(foreground="#000000")
        self.Shape_Entry2_8.configure(highlightbackground="#d9d9d9")
        self.Shape_Entry2_8.configure(highlightcolor="black")
        self.Shape_Entry2_8.configure(insertbackground="black")
        self.Shape_Entry2_8.configure(selectbackground="#c4c4c4")
        self.Shape_Entry2_8.configure(selectforeground="black")

        self.Adhesion_Entry2_9 = tk.Entry(top)
        self.Adhesion_Entry2_9.place(relx=0.18, rely=0.363, height=44
                , relwidth=0.514)
        self.Adhesion_Entry2_9.configure(background="white")
        self.Adhesion_Entry2_9.configure(disabledforeground="#a3a3a3")
        self.Adhesion_Entry2_9.configure(font="TkFixedFont")
        self.Adhesion_Entry2_9.configure(foreground="#000000")
        self.Adhesion_Entry2_9.configure(highlightbackground="#d9d9d9")
        self.Adhesion_Entry2_9.configure(highlightcolor="black")
        self.Adhesion_Entry2_9.configure(insertbackground="black")
        self.Adhesion_Entry2_9.configure(selectbackground="#c4c4c4")
        self.Adhesion_Entry2_9.configure(selectforeground="black")

        self.Epithelial_Entry2_10 = tk.Entry(top)
        self.Epithelial_Entry2_10.place(relx=0.18, rely=0.45, height=44
                , relwidth=0.514)
        self.Epithelial_Entry2_10.configure(background="white")
        self.Epithelial_Entry2_10.configure(disabledforeground="#a3a3a3")
        self.Epithelial_Entry2_10.configure(font="TkFixedFont")
        self.Epithelial_Entry2_10.configure(foreground="#000000")
        self.Epithelial_Entry2_10.configure(highlightbackground="#d9d9d9")
        self.Epithelial_Entry2_10.configure(highlightcolor="black")
        self.Epithelial_Entry2_10.configure(insertbackground="black")
        self.Epithelial_Entry2_10.configure(selectbackground="#c4c4c4")
        self.Epithelial_Entry2_10.configure(selectforeground="black")

        self.Bare_Entry2_11 = tk.Entry(top)
        self.Bare_Entry2_11.place(relx=0.18, rely=0.525, height=44
                , relwidth=0.514)
        self.Bare_Entry2_11.configure(background="white")
        self.Bare_Entry2_11.configure(disabledforeground="#a3a3a3")
        self.Bare_Entry2_11.configure(font="TkFixedFont")
        self.Bare_Entry2_11.configure(foreground="#000000")
        self.Bare_Entry2_11.configure(highlightbackground="#d9d9d9")
        self.Bare_Entry2_11.configure(highlightcolor="black")
        self.Bare_Entry2_11.configure(insertbackground="black")
        self.Bare_Entry2_11.configure(selectbackground="#c4c4c4")
        self.Bare_Entry2_11.configure(selectforeground="black")

        self.Bland_Entry2_12 = tk.Entry(top)
        self.Bland_Entry2_12.place(relx=0.18, rely=0.613, height=44
                , relwidth=0.514)
        self.Bland_Entry2_12.configure(background="white")
        self.Bland_Entry2_12.configure(disabledforeground="#a3a3a3")
        self.Bland_Entry2_12.configure(font="TkFixedFont")
        self.Bland_Entry2_12.configure(foreground="#000000")
        self.Bland_Entry2_12.configure(highlightbackground="#d9d9d9")
        self.Bland_Entry2_12.configure(highlightcolor="black")
        self.Bland_Entry2_12.configure(insertbackground="black")
        self.Bland_Entry2_12.configure(selectbackground="#c4c4c4")
        self.Bland_Entry2_12.configure(selectforeground="black")

        self.Normal_Entry2_13 = tk.Entry(top)
        self.Normal_Entry2_13.place(relx=0.18, rely=0.688, height=44
                , relwidth=0.514)
        self.Normal_Entry2_13.configure(background="white")
        self.Normal_Entry2_13.configure(disabledforeground="#a3a3a3")
        self.Normal_Entry2_13.configure(font="TkFixedFont")
        self.Normal_Entry2_13.configure(foreground="#000000")
        self.Normal_Entry2_13.configure(highlightbackground="#d9d9d9")
        self.Normal_Entry2_13.configure(highlightcolor="black")
        self.Normal_Entry2_13.configure(insertbackground="black")
        self.Normal_Entry2_13.configure(selectbackground="#c4c4c4")
        self.Normal_Entry2_13.configure(selectforeground="black")

        self.Mitoses_Entry2_14 = tk.Entry(top)
        self.Mitoses_Entry2_14.place(relx=0.18, rely=0.763, height=44
                , relwidth=0.514)
        self.Mitoses_Entry2_14.configure(background="white")
        self.Mitoses_Entry2_14.configure(disabledforeground="#a3a3a3")
        self.Mitoses_Entry2_14.configure(font="TkFixedFont")
        self.Mitoses_Entry2_14.configure(foreground="#000000")
        self.Mitoses_Entry2_14.configure(highlightbackground="#d9d9d9")
        self.Mitoses_Entry2_14.configure(highlightcolor="black")
        self.Mitoses_Entry2_14.configure(insertbackground="black")
        self.Mitoses_Entry2_14.configure(selectbackground="#c4c4c4")
        self.Mitoses_Entry2_14.configure(selectforeground="black")

        self.predict = tk.Button(top)
        self.predict.place(relx=0.37, rely=0.888, height=73, width=276)
        self.predict.configure(activebackground="#ececec")
        self.predict.configure(activeforeground="#000000")
        self.predict.configure(background="#ff0000")
        self.predict.configure(borderwidth="6")
        self.predict.configure(disabledforeground="#a3a3a3")
        self.predict.configure(font=font10)
        self.predict.configure(foreground="#000000")
        self.predict.configure(highlightbackground="#d9d9d9")
        self.predict.configure(highlightcolor="black")
        self.predict.configure(pady="0")
        self.predict.configure(text='''Predict''')
        self.predict.configure(command = self.BCD_test)

if __name__ == '__main__':
    vp_start_gui()





